### ISSUE TITLE
Reorganize Repo

### ISSUE THREAD

**Issue by danielcasto** [danielcasto/AIRPrediction#1]
Remove all unnecessary files that are not involved in the execution of the program. Reorganize files so that packaging is easier

**Comment by DerekPena** [comment]
Suggested File Deletions: 
client.py 
server.py
forecast_flask_app.py
air_forecasting_service.py
air_forecasting_service1.py
Flaskrun.txt
The folders src and Prototype Demo Codes

**Comment by danielcasto** [comment]
I deleted those suggested files.
