### ISSUE TITLE
Begin Documentation of Files

### ISSUE THREAD

**Issue by DerekPena** [danielcasto/AIRPrediction#5]
We will need to use sphinx for the documentation of our framework as well as follow the style of shown in the lecture.

Lecture: 04B Debugging Tools @ 1:11:45

**Comment by danielcasto** [comment]
I configured Sphinx for our project. We can now add docstrings to the files so that documentation can be auto generated.

**Comment by DerekPena** [comment]
In code documentation added to the driver file.

**Comment by DerekPena** [comment]
In code documentation added to all python files. Working on sphinx documentation.

**Comment by DerekPena** [comment]
Documentation completed by Colin. Closing Issue.
