### ISSUE TITLE
Sample App Improvements

### ISSUE THREAD

**Issue by colinnaehr** [danielcasto/AIRPrediction#6]
Improve UI and other parts of sample app for better demonstration

**Comment by danielcasto** [comment]
What kind of specific improvements would we like to make?

**Comment by colinnaehr** [comment]
Toggle between different forecasting methods, and improvements to the UI look if given the go ahead tomorrow. If this is not necessary, then the issue can be closed.

**Comment by colinnaehr** [comment]
Final changes: Buttons for Prophet and Arima, and comparison of both; addition of county and state, and progress notification

**Comment by DerekPena** [comment]
Added state updates to the sample app. Minor appearance tweaks. Sample app is essentially finalized with the potential for minor tweaks or bug fixes. Closing Issue.
